[tools]
hk = "latest"
pkl = "latest"
bun = "latest"

[tasks.prepare]
description = "Prepare for release (Run from GitHub Actions)"
run = """jq --arg v "{{option(name='version')}}" '.version = $v' package.json > tmp.json && mv tmp.json package.json"""

[tasks.publish]
description = "Publish to JSR (Run from GitHub Actions)"
run = "npx jsr publish"
