[tools]
hk = "latest"
pkl = "latest"
bun = "latest"

[tasks.build]
description = "Build CLI"
run = [
  "bun run build",
]

[tasks.prepare]
description = "Prepare for release (Run from GitHub Actions)"
run = [
  """jq --arg v "{{option(name='version')}}" '.version = $v' package.json > tmp.json && mv tmp.json package.json""",
  "bun install",
  "mise run build",
]
